export const palette = {
  blueDeep: '#1A3A5C',
  blueMid: '#2563A8',
  blueBright: '#3B82F6',
  blueLight: '#BFDBFE',
  bluePale: '#EFF6FF',
  teal: '#0EA5C9',
  tealLight: '#CFFAFE',
  mint: '#10B981',
  mintLight: '#D1FAE5',
  amber: '#F59E0B',
  amberLight: '#FEF3C7',
  rose: '#F43F5E',
  roseLight: '#FFE4E6',
  violet: '#7C3AED',
  violetLight: '#EDE9FE',
  white: '#FFFFFF',
  slate900: '#0F1F35',
  slate700: '#3D5A7A',
  slate500: '#7B96B2',
  slate300: '#E2EAF4',
  slate100: '#F8FAFF',
  slate050: '#F0F4FA',
  danger: '#DC2626',
} as const;

export const colors = {
  background: palette.slate050,
  surface: palette.white,
  surfaceElevated: palette.slate100,
  border: palette.slate300,
  textPrimary: palette.slate900,
  textSecondary: palette.slate700,
  textMuted: palette.slate500,
  primary: palette.blueBright,
  primaryDark: palette.blueDeep,
  primarySoft: palette.bluePale,
  info: palette.teal,
  success: palette.mint,
  warning: palette.amber,
  danger: palette.rose,
  accentTeal: palette.teal,
  accentMint: palette.mint,
  accentAmber: palette.amber,
  accentRose: palette.rose,
  accentViolet: palette.violet,
} as const;
